#!/usr/bin/env python3
import argparse
import subprocess

REPLICA_SERVERS = {
    'cdn-http3.khoury.northeastern.edu': '45.33.55.171',
    'cdn-http4.khoury.northeastern.edu': '170.187.142.220', 
    'cdn-http7.khoury.northeastern.edu': '213.168.249.157', 
    'cdn-http11.khoury.northeastern.edu': '139.162.82.207', 
    'cdn-http14.khoury.northeastern.edu': '45.79.124.209', 
    'cdn-http15.khoury.northeastern.edu': '192.53.123.145', 
    'cdn-http16.khoury.northeastern.edu': '192.46.221.203',
}

DNS_SERVER = 'cdn-dns.khoury.northeastern.edu'

def main(args):
    '''
    This is the main function that runs the CDN. It starts the HTTP servers on each replica server and the DNS server.
    '''
    print("** RUNNING CDN **")
     # SSH and run the DNS server
    print(f"** Starting DNS server on {DNS_SERVER} ** ")
    subprocess.Popen(f'ssh -i {args.keyfile} {args.username}@{DNS_SERVER} "python3 dnsserver -p {args.port} -n {args.name}"', shell=True)

    # SSH and run the HTTP server on each replica server
    for server in REPLICA_SERVERS:
        print(f"** Starting HTTP server on {server} ** ")
        subprocess.Popen(f'ssh -i {args.keyfile} {args.username}@{REPLICA_SERVERS[server]} "python3 httpserver -p {args.port} -o {args.origin}"', shell=True)

    print("** DONE! :) **")

if __name__ == '__main__':
    # Parse the arguments
    parser = argparse.ArgumentParser(description='Deploy CDN')
    parser.add_argument('-p', '--port', required=True, type=int, help='Port number to bind HTTP server to')
    parser.add_argument('-o', '--origin', required=True, type=str, help='Origin server to fetch content from')
    parser.add_argument('-n', '--name', required=True, type=str, help='CDN-specific domain name to translate')
    parser.add_argument('-u', '--username', required=True, type=str, help='Username for logging into cloud servers')
    parser.add_argument('-i', '--keyfile', required=True, type=str, help='Path to private key for logging into cloud servers')
    args = parser.parse_args()
    main(args)