#!/usr/bin/env -S python3 -u


'''
This is just a testing file I am using to help with parsing
'''
def main():
  msg = {
    "192.168.1.0": {
      "10.0.0.1": {
      "netmask": "255.255.255.0",
      "dst": "192.168.0.1",
      "ASPath": [
            16,
            1
              ],
      "localpref": 100,
      "origin": "EGP",
      "selfOrigin": True
      },
      
      "10.2.0.1": {
      "netmask": "255.255.255.0",
      "dst": "192.168.0.1",
      "ASPath": [
            16,
            1
              ],
      "localpref": 100,
      "origin": "EGP",
      "selfOrigin": True
      } 
    },
    
    "192.278.1.0": {
      "10.0.0.1": {
      "netmask": "255.255.255.0",
      "dst": "192.168.0.1",
      "ASPath": [
            16,
            1
              ],
      "localpref": 100,
      "origin": "EGP",
      "selfOrigin": True
      },
      
      "10.2.0.1": {
      "netmask": "255.255.255.0",
      "dst": "192.168.0.1",
      "ASPath": [
            16,
            1
              ],
      "localpref": 100,
      "origin": "EGP",
      "selfOrigin": True
      } 
    }
  }

  dst = "192.278.1.0"
    
  for i in msg:
    if i == dst:
      

if __name__ == "__main__":
  main()
  



  
